# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u041a\u043b\u0430\u0441\u0441',
                'verbose_name_plural': '\u041a\u043b\u0430\u0441\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('grades', models.ManyToManyField(blank=True, to='mediterra.Grade', verbose_name='\u041a\u043b\u0430\u0441\u0441\u044b')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'verbose_name': '\u0423\u0447\u0435\u043d\u0438\u043a',
                'verbose_name_plural': '\u0423\u0447\u0435\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('specializations', models.ManyToManyField(to='mediterra.Specialization', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'verbose_name': '\u0423\u0447\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u0423\u0447\u0438\u0442\u0435\u043b\u044f',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediterra.Specialization', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediterra.Teacher', verbose_name='\u0423\u0447\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
